### ISSUE TITLE
SPI communication with STM32 using linx

### ISSUE THREAD

**Issue by L1ikhith** [MakerHub/LINX#128]
Hello,
i was getting errors with one of the SPI functions in LinxWiringDevice. The issue is  in LinxWiringDevice. cpp, the bitOrder in  SPI.setBitOrder(bitOrder)  is defined as unsigned char but in STM32 SPI file it was defined as Enum. Is there a way to make the function variable as Enum instead of unsigned char 

_REF:_
**SPI.cpp:**

`void SPIClass::setBitOrder(BitOrder bitOrder)
{
  _spiSettings.bitOrder = bitOrder;

  spi_init(&_spi, _spiSettings.clockFreq,
           _spiSettings.dataMode,
           _spiSettings.bitOrder);
}`

**Wiring_constants.h**

`enum BitOrder {
  LSBFIRST = 0,
  MSBFIRST = 1
};`

**LinuxWiringDevice.cpp**
`int LinxWiringDevice::SpiSetBitOrder(unsigned char channel, unsigned char bitOrder)
{
	SPI.setBitOrder(bitOrder);
	return 0;
}
`

**Comment by samkristoff** [comment]
Can you link to the SPI.cpp file you're referring to?

**Comment by samkristoff** [comment]
Is this the BitOrder you're rerring to:
https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/cores/maple/wirish_constants.h

Can you ellaborate on the erorrs?  Are you building the C++ code and getting compile time errors, runtime errors, etc?

Thanks!

**Comment by L1ikhith** [comment]
Hello @samkristoff thanks for the quick reply, here are the links to the files 
**SPI.cpp**: [https://github.com/stm32duino/Arduino_Core_STM32/blob/main/libraries/SPI/src/SPI.cpp](url)
**Wiring_constants.h** :[https://github.com/stm32duino/Arduino_Core_STM32/blob/main/cores/arduino/wiring_constants.h](url)

**ERROR screenshot**
![Screenshot (1)](https://github.com/MakerHub/LINX/assets/45322471/7b18ceb8-7307-49a6-bb5f-54c09f9bac3d)

**Comment by samkristoff** [comment]
Hey, can you just cast the bitOrder to unsigned char on line 310 like this:

`SPI.setBitOrder((unsigned char)bitOrder);`

**Comment by L1ikhith** [comment]
@samkristoff i think i cant able to cast the bitOrder to unsigned char, in the wiring_constant bitOrder was declared as enum and the SPI function was wrote in terms as enum as input

**Comment by L1ikhith** [comment]
@samkristoff  i think i cant able to cast unsigned char for bitOrder, the function SPI.setBitOrder was designed based on enum as input for the function.
