### ISSUE TITLE
Sensor Request - MPU-6050

### ISSUE THREAD

**Issue by Nathan--B** [MakerHub/LINX#35]
Add support for the MEMS Accelerometer/Gyro MPU-6050 (I2C).

**Comment by Nathan--B** [comment]
The device address handling after switching to an enum was not properly changed for all subVI's for this sensor.  It is correct in Open.vi but none of the rest of them.

**Comment by samkristoff** [comment]
This will be fixed in 2.0.0.94 (or 2.0.0.95 depending on who builds first).
