### ISSUE TITLE
Firmware Wizard does not work when VISA resource alias is changed in MAX

### ISSUE THREAD

**Issue by Nathan--B** [MakerHub/LINX#97]
When you change the alias for a VISA resource in NI MAX (i.e. rename it to something other than "COM#"), Windows does not recognize the new alias when AVRDude tries to upload the hex file to the device.

I created a quick fix here:  https://www.labviewmakerhub.com/forums/viewtopic.php?f=12&t=955#p5659

I'm not entirely sure that this is the most robust solution though.

**Comment by samkristoff** [comment]
Added to LINX 2.1.
